FUNCTION(ADD_NO_COMMENT_TEST TEST_NAME)
    ADD_EXECUTABLE(${TEST_NAME}.exe ${PROJECT_SOURCE_DIR}/test/${TEST_NAME}.cc)
    TARGET_LINK_LIBRARIES(${TEST_NAME}.exe no_comment)
    TARGET_LINK_LIBRARIES(${TEST_NAME}.exe ${DEAL_II_TARGET})
    TARGET_LINK_LIBRARIES(${TEST_NAME}.exe ${DataTransferKit_LIBRARIES})
    TARGET_LINK_LIBRARIES(${TEST_NAME}.exe ${Boost_LIBRARIES})
    IF(ARGN)
        SET(NUMBER_OF_PROCESSES_TO_RUN ${ARGN})
    ELSE()
        SET(NUMBER_OF_PROCESSES_TO_RUN 1)
    ENDIF()
    FOREACH(N_PROCS ${NUMBER_OF_PROCESSES_TO_RUN})
        ADD_TEST(
            NAME ${TEST_NAME}_${N_PROCS}_procs
            COMMAND ${MPIEXEC} -np ${N_PROCS} ${TEST_NAME}.exe
            )
    ENDFOREACH()
ENDFUNCTION()
